myrsrcmngr/myrsrcmngr/urls.py
from django.contrib import admin
from django.urls import path, include
from myrsrcmngr import views
from users.views import register, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resources/', views.Resource_list),
    path('', include('website.urls')),
    path('register/', register.as_view(), name='register'),
    #path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout-view'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('users.urls')),
]

myrsrcmngr/users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path('<int:pk>/', views.ProfileDetailView.as_view(), name = 'profile-home'),
    path('<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('<int:pk>/delete', views.ProfileDeleteView.as_view(), name='profile-delete'),
]

myrsrcmngr/website/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'website'
urlpatterns = [
    #Dashboard
    path('', views.dashboard, name='index'),
    
    #Dashboard API for AJAX calls
    path('dashboard/api/dismissed/', views.dashboard_dismiss, name='dashboard-dismiss'),
    path('dashboard/api/changes/', views.dashboard_changes, name='dashboard-changes'),
    path('changes/', views.dashboard_changes_table, name='changes-only'),
    path('dashboard/api/scans/', views.dashboard_scans, name='dashboard-scans'),
    
    #Scans CRUD
    path('scans/', views.ScansListView.as_view(), name='scans-list'),
    path('scans/create', views.ScanCreateView.as_view(), name='new-scan'),
    path('scans/<int:pk>', views.ScanDetailView.as_view(), name='scan-detail'),
    path('scans/<int:pk>/edit', views.ScanUpdateView.as_view(), name='edit-scan'),
    path('scans/<int:pk>/delete', views.ScanDeleteView.as_view(success_url=reverse_lazy('website:scans-list')), name='delete-scan'),
    
    #Scans API for AJAX calls
    path('scans/api/<int:pk>/', views.ScanProgressView.as_view(), name='scan-progress'),
    path('scans/api/toggle/<int:pk>/', views.scan_toggle, name='scan-toggle'),
    path('scans/api/refresh/scans/<int:pk>/', views.scan_refresh, name='reports-refresh'),
    path('scans/api/refresh/scans/', views.scanlist_refresh, name='scans-refresh'),
    path('scans/api/refresh/totals/', views.scanlist_totals_refresh, name='scans-totals'),

    #Resource groups CRUD
    path('groups/', views.ResourcegroupsListView.as_view(), name='groups-list'),
    path('groups/create', views.ResourcegroupCreateView.as_view(), name='new-group'),
    path('groups/<int:pk>/', views.ResourcegroupDetailView.as_view(), name='groups-detail'),
    path('groups/<int:pk>/edit', views.ResourcegroupUpdateView.as_view(), name='edit-group'),
    path('groups/<int:pk>/delete', views.ResourcegroupDeleteView.as_view(success_url=reverse_lazy('website:groups-list')), name='delete-group'),
    
    #Resource groups API for AJAX calls
    path('groups/api/refresh/groups/', views.grouplist_refresh, name='groups-refresh'),
    path('groups/api/refresh/scans/<int:pk>/', views.scans_group_refresh, name='scans-group-refresh'),
    path('groups/api/refresh/totals/', views.grouplist_totals_refresh, name='groups-totals'),
    path('groups/api/refresh/changes/<int:pk>/', views.group_changes_refresh, name='groups-changes'),
    path('groups/api/refresh/hosts/<int:pk>/', views.hostsgroup_refresh, name='hosts-refresh'),

    #Hosts CRUD
    path('hosts/', views.HostsListView.as_view(), name='hosts-list'),
    path('hosts/<int:pk>/', views.HostDetailView.as_view(), name='hosts-detail'),
    path('hosts/<int:pk>/edit', views.HostUpdateView.as_view(), name='edit-host'),
    
    #Hosts API for AJAX calls
    path('hosts/api/refresh/totals/', views.hosts_totals_refresh, name='hosts-totals'),
    path('hosts/api/refresh/hosts/', views.hosts_refresh, name='hosts-all-refresh'),
    path('hosts/api/refresh/changes/<int:pk>/', views.host_changes_refresh, name='host-changes'),
    path('hosts/api/refresh/services/<int:pk>/', views.host_services_refresh, name='host-services'),
    
    #Reports CRUD
    path('reports/', views.ReportsListView.as_view(), name='reports-list'),
    path('reports/<int:pk>', views.ReportDetailView.as_view(), name='report-detail'),
    path('reports/<int:pk>/download/', views.download_report, name='download_report'),
    
    #Reports API for AJAX calls 
    path('reports/api/toggle/<int:pk>/', views.set_standard_report, name='set-standard-report'),
    path('reports/api/refresh/totals/', views.reports_totals_refresh, name='reports-totals'),
    path('reports/api/refresh/reports/', views.reports_refresh, name='reports-all-refresh'),
    
    #Services CRUD
    path('services/<int:pk>', views.ServiceDetailView.as_view(), name='service-detail'),
    
    #Services API for AJAX calls
    
    
    #Search
    path('search/', views.GlobalSearch, name='search'),
    
    #Scans list JSON response
    path('scans/json/', views.scans_list),
    
    #Chart refresh API
    path('groups/api/chart/', views.groups_piechart, name='groups-chart'),
    path('scans/api/chart/', views.scans_chart, name='scans-chart'),
    path('hosts/api/chart/', views.hosts_chart, name='hosts-chart'),
    path('reports/api/chart/', views.reports_chart, name='reports-chart'),
    path('dashboard/api/chart/', views.dashboard_chart, name='dashboard-chart'),
]

myrsrcmngr/website/views.py
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import JsonResponse
from django.contrib.humanize.templatetags.humanize import naturaltime
from .serializers import ScansSerializer, ReportsSerializer, ResourcegroupsSerializer, HostsSerializer, ServicesSerializer
from rest_framework.decorators import api_view
from .owner import OwnerCreateView, OwnerUpdateView, OwnerDeleteView, GroupOwnerCreateView, GroupOwnerUpdateView, GroupOwnerDeleteView, HostOwnerUpdateView
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseNotAllowed
import os
import random
from django.db.models import Q
from django.utils import timezone
import logging
from django.db.models import Count



# Create your views here.
from .models import scans, hosts, reports, resourcegroups, services, changes
logger = logging.getLogger(__name__)

def index(request):
    con = {}
    rreport = None
    for rgroup in resourcegroups.objects.all().order_by('-updated_at')[:5]:
        
        try:
            rreport = rgroup.reports_set.latest('id')
            groupname = rgroup.name
            con[groupname] = rreport
        except:
            rreport = None
    context = {
        'con': con
    }
    return render(request, 'index.html', context)

def dashboard_changes_table(request):
    if request.method == 'GET':
        eachchanges = {}
        allchanges = []
        mainchanges = {'total': 0,
                        'changes': [{
                                    'main_address':'',
                                    'group_name':'',
                                    'group_id':0,
                                    'host_id':0,
                                    'report_date':'',
                                    'report_id':0,
                                    'attribute': '',
                                    'new_value': '',
                                    },
                                ]
                    }        
        #In order to relieve some data amount concerns, select just the last 100 successful reports
        reports_list = reports.objects.all().filter(parse_success=True).order_by('-id')[:100]

        #for each report, find the notable changes (status, state, os_fingerprint) that have not been dismissed, and are not the elapsed time
        #Further filter down for those changes that have host indicated
        filteredChanges = changes.objects.filter(cur_report__in=reports_list)
        filteredChanges = filteredChanges.exclude(dismissed=True).exclude(attribute='elapsed').exclude(host=None)
        filteredChanges = filteredChanges.filter(Q(attribute='status') | Q(attribute='state') | Q(attribute='os_fingerprint'))
        for change in filteredChanges:
            host = change.host
            group = host.resourcegroup
            eachchanges['main_address'] = host.main_address
            eachchanges['group_name'] = group.name
            eachchanges['group_id'] = group.id
            eachchanges['host_id'] = host.id
            eachchanges['report_date'] = change.cur_report.f_endtime_str()
            eachchanges['report_id'] = change.cur_report.id
            eachchanges['attribute'] = change.attribute
            if change.attribute == 'state' and change.cur_val == 'open':
                eachchanges['new_value'] = change.service.name_conc
            elif change.attribute == 'state':
                eachchanges = {}
                continue
            else:
                eachchanges['new_value'] = change.cur_val
            allchanges.append(eachchanges)
            eachchanges = {}
        mainchanges['total'] = len(allchanges)
        mainchanges['changes'] = allchanges
        return render(request, 'selected_changes.html', {'changes':mainchanges})

@api_view(['POST'])
def dashboard_dismiss(request):
    if request.method == 'POST':
        # get the last 100 reports
        last_100_reports = reports.objects.all().order_by('-id')[:100]
        # get all changes that relate to the last 100 reports
        filteredchanges = changes.objects.filter(cur_report__in=last_100_reports)
        # set the 'dismissed' attribute to True for all changes
        filteredchanges.update(dismissed=True)
        # return a JSON response indicating that the changes have been dismissed
        return JsonResponse({'dismissed': True})

@api_view(['GET'])
def dashboard_changes(request):
    if request.method == 'GET':
        eachchanges = {}
        allchanges = []
        mainchanges = {'total': 0,
                        'changes': [{
                                    'main_address':'',
                                    'group_name':'',
                                    'group_id':0,
                                    'host_id':0,
                                    'report_date':'',
                                    'report_id':0,
                                    'attribute': '',
                                    'new_value': '',
                                    },
                                ]
                    }        
        #In order to relieve some data amount concerns, select just the last 100 successful reports
        reports_list = reports.objects.all().filter(parse_success=True).order_by('-id')[:100]

        #for each report, find the notable changes (status, state, os_fingerprint) that have not been dismissed, and are not the elapsed time
        #Further filter down for those changes that have host indicated
        filteredChanges = changes.objects.filter(cur_report__in=reports_list)
        filteredChanges = filteredChanges.exclude(dismissed=True).exclude(attribute='elapsed').exclude(host=None)
        filteredChanges = filteredChanges.filter(Q(attribute='status') | Q(attribute='state') | Q(attribute='os_fingerprint'))
        for change in filteredChanges:
            host = change.host
            group = host.resourcegroup
            eachchanges['main_address'] = host.main_address
            eachchanges['group_name'] = group.name
            eachchanges['group_id'] = group.id
            eachchanges['host_id'] = host.id
            eachchanges['report_date'] = change.cur_report.f_endtime_str()
            eachchanges['report_id'] = change.cur_report.id
            eachchanges['attribute'] = change.attribute
            if change.attribute == 'state' and change.cur_val == 'open':
                eachchanges['new_value'] = change.service.name_conc
            elif change.attribute == 'state':
                eachchanges = {}
                continue
            else:
                eachchanges['new_value'] = change.cur_val
            allchanges.append(eachchanges)
            eachchanges = {}
        mainchanges['total'] = len(allchanges)
        mainchanges['changes'] = allchanges
        return JsonResponse({"data":mainchanges})


def dashboard(request):
    con = {}
    rreport = None
    report_changes = {}
    for rgroup in resourcegroups.objects.all().order_by('-updated_at'):
        
        try:
            rreport = rgroup.reports_set.latest('id')
            groupname = rgroup.name
            rchanges = rreport.changes_set.all().exclude(attribute='elapsed')
            changes_count = rchanges.count()
            if rchanges:
                report_changes['hosts_changed'] = 0
                report_changes['hosts_added'] = 0
                report_changes['hosts_removed'] = 0
                report_changes['services_changed'] = 0
                report_changes['services_added'] = 0
                report_changes['services_removed'] = 0
                report_changes['hosts_up'] = None
                report_changes['hosts_down'] = None
                report_changes['hosts_total'] = None
                counter = 0
                for change in rchanges:
                    counter = counter + 1
                    if change.attribute == 'hosts_up':
                        if change.prev_val is None:
                            change.prev_val = 0
                        report_changes['hosts_up'] = int(change.cur_val) - int(change.prev_val)
                    elif change.attribute == 'hosts_down':
                        if change.prev_val is None:
                            change.prev_val = 0
                        report_changes['hosts_down'] = int(change.cur_val) - int(change.prev_val)
                    elif change.attribute == 'hosts_total':
                        if change.prev_val is None:
                            change.prev_val = 0
                        report_changes['hosts_total'] = int(change.cur_val) - int(change.prev_val)
                    elif change.status == 'CHANGED' and change.host is not None and change.service is None:
                        report_changes['hosts_changed'] = report_changes['hosts_changed'] + 1
                    elif change.status == 'ADDED' and change.host is not None and change.service is not None:
                        report_changes['services_added'] = report_changes['services_added'] + 1
                    elif change.status == 'CHANGED' and change.host is not None and change.service is not None:
                        report_changes['services_changed'] = report_changes['services_changed'] + 1
                    elif change.status == 'REMOVED' and change.host is not None and change.service is not None:
                        report_changes['services_removed'] = report_changes['services_removed'] + 1
                    elif change.status == 'REMOVED' and change.host is not None and change.service is None:
                        report_changes['hosts_removed'] = report_changes['hosts_removed'] + 1
                    elif change.status == 'ADDED' and change.host is not None and change.service is None:
                        report_changes['hosts_added'] = report_changes['hosts_added'] + 1

myrsrcmngr/website/templates/website/scans_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid px-4">
    <h2 class="d-inline-block my-auto mt-4">Scan: {{ scans.scanName | upper }}</h2>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Group: 
            <a href="{% url 'website:groups-detail' scans.resourcegroup.id %}">{{ scans.resourcegroup | upper }}</a>
        </li>
    </ol>
    <div class="row">
        <div class="col-xl-6 col-md-6">
            <div class="card bg-info text-white mb-4">
                <div class="card-header">
                    <ul class="nav nav-tabs float-xs-left" id="myTab" role="tablist">
                        <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="info-tab" data-bs-toggle="tab" data-bs-target="#info-tab-pane" type="button" role="tab" aria-controls="info-tab-pane" aria-selected="true">Info</button>
                        </li>
                        {% if scans.scanAuthor == user or user.is_superuser %}
                        <li class="nav-item" role="presentation">
                        <button class="nav-link" id="options-tab" data-bs-toggle="tab" data-bs-target="#options-tab-pane" type="button" role="tab" aria-controls="options-tab-pane" aria-selected="false">Options</button>
                        </li>
                        {% else %}
                        <li class="nav-item" role="presentation">
                        <button class="nav-link" id="options-tab" data-bs-toggle="tab" data-bs-target="#options-tab-pane" type="button" role="tab" aria-controls="options-tab-pane" aria-selected="false" disabled>Options</button>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="info-tab-pane" role="tabpanel" aria-labelledby="info-tab" tabindex="0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-6">Last Executed:</div>
                                    <div class="col-6 text-right" id="last-exec-scanprogress">{{ scans.last_executed }}</div>
                                </div>
                                <div class="row">
                                    <div class="col-6">Parameters:</div>
                                    <div class="col-6 text-right">{{ scans.ScanTemplate }}</div>
                                </div>  
                                <div class="row">
                                    <div class="col-6">Schedule:</div>
                                    <div class="col-6 text-right">{{ scans.formatted_schedule }}</div>
                                </div>                           
                            </div>
                        </div>
                        <div class="tab-pane fade" id="options-tab-pane" role="tabpanel" aria-labelledby="options-tab" tabindex="0">
                            <div class="card-body">
                                {% if scans.scanAuthor == user or user.is_superuser %}
                                    {% if scans.active %}
                                        <button id="toggle-button" scan-ajax-target="{% url 'website:scan-toggle' scans.id %}" value="{{scans.active}}" class="btn btn-danger d-inline-block my-auto">TURN OFF</button>
                                        <input type="hidden" id="active" value="1">
                                    {% else %}
                                        <button id="toggle-button" scan-ajax-target="{% url 'website:scan-toggle' scans.id %}" value="{{scans.active}}" class="btn btn-success d-inline-block my-auto">TURN ON</button>
                                        <input type="hidden" id="active" value="0">
                                    {% endif %}
                                    <a href="{% url 'website:edit-scan' scans.id %}" id="editButton" class="btn btn-primary">Edit</a>
                                    <a href="{% url 'website:delete-scan' scans.id %}" id="deleteButton" class="btn btn-primary">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <div class="small text-white">Created by <a class="small text-white" href="{% url 'users:profile-home' scans.scanAuthor.profile.id %}">{{ scans.scanAuthor }}</a> on {{ scans.create_date | date }}</div>
                    </div>
            </div>
        </div>
                
        <div class="col-xl-6 col-md-6">
            <div class="card bg-secondary text-white mb-4">
                <div class="card-header">
                    <ul class="nav nav-tabs float-xs-left" id="myTab2" role="tablist">
                        <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="status-tab" data-bs-toggle="tab" data-bs-target="#status-tab-pane" type="button" role="tab" aria-controls="status-tab-pane" aria-selected="true">Status</button>
                        </li>
                        <li class="nav-item" role="presentation">
                        <button class="nav-link" id="stats-tab" data-bs-toggle="tab" data-bs-target="#stats-tab-pane" type="button" role="tab" aria-controls="stats-tab-pane" aria-selected="false">Stats</button>
                        </li>
                    </ul>
                </div>
                    <div class="tab-content" id="myTabContent2">
                        <div class="tab-pane fade show active" id="status-tab-pane" role="tabpanel" aria-labelledby="status-tab" tabindex="0">
                            <div class="card-body">
                                <div class="card-body" id="stable-scanprogress">
                                    <div class="row">
                                        <div class="col-6">Scan is: </div>
                                        <div class="col-6 text-right" id="active-scanprogress">{{ scans.formatted_active }}</div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-6">Execution:</div>
                                        <div class="col-6 text-right" id="status-scanprogress">{{ scans.formatted_status }}</div>
                                    </div>
                                    {% if scans.formatted_active == "ON" %}
                                    <div class="row" id="next-exec-scanprogress">
                                        <div class="col-6">Next Execution:</div>
                                        <div class="col-6 text-right" id="next-val-scanprogress">{{ scans.formatted_next_execution_at }}</div>
                                    </div>
                                    {% endif %}
                                </div>
                                <div class="card-body" id="scanprogress" data-ajax-target="{% url 'website:scan-progress' scans.id %}">
                                    <div class="row">
                                        <div class="col-6">Task Name:</div>
                                        <div class="col-6 text-right" id="task-name-scanprogress">{{ scans.task_name }}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-6">Task Status: </div>
                                        <div class="col-6 text-right" id="task-status-scanprogress">{{ scans.task_status }}</div>
                                    </div> 
                                    <div class="progress">
                                        <div class="progress-bar" id="task-progress-scanprogress" role="progressbar" style="width: 0%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">0%</div>
                                    </div>                 
                                </div>
                            </div>            
                        </div>
                        <div class="tab-pane fade" id="stats-tab-pane" role="tabpanel" aria-labelledby="stats-tab" tabindex="0">
                            <div class="card-body">
                                <div class="card-body" id="statslist">
                                    <div class="row">
                                        <div class="col-6">Reports Generated: </div>
                                        <div class="col-6 text-right" id="statslist-report-count">0</div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-6">Average Execution Time:</div>
                                        <div class="col-6 text-right" id="statslist-exec-time">0</div>
                                    </div>
                                </div>
                            </div>  
                        </div>
                    </div>
            </div>
        </div>

    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Latest reports for <b>{{ scans.scanName | title }}</b>
        </div>
        <div class="card-body">
        {% if reports %}
            <table id="datatablesSimple4" class="table" report-url="{% url 'website:reports-refresh' scans.id %}">
                <thead>
                    <tr>
                        <th>Started at</th>
                        <th>Ended at</th>
                        <th>Duration</th>
                        <th>Number of Services</th>
                        <th>Hosts Up</th>
                        <th>Hosts Down</th>
                        <th>Hosts Total</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Started at</th>
                        <th>Ended at</th>
                        <th>Duration</th>
                        <th>Number of Services</th>
                        <th>Hosts Up</th>
                        <th>Hosts Down</th>
                        <th>Hosts Total</th>
                        <th>Link</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for report in reports %}
                    <tr>
                        <td>{{ report.f_started_str }}</td>
                        <td>{{ report.f_endtime_str }}</td>
                        <td>{{ report.elapsed }} seconds</td>
                        <td>{{ report.num_services }}</td>
                        <td>{{ report.hosts_up }}</td>
                        <td>{{ report.hosts_down }}</td>
                        <td>{{ report.hosts_total }}</td>
                        <td><a href="{% url 'website:report-detail' report.id %}">View</a></td>
                    </tr>
                    {% endfor %}
               

                </tbody>
            </table>
        {% else %}
            <p>'There are no reports generated by scan "{{ scans.scanName | title }}" in the database.' </p>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'website/js/scanupdate.js' %}"></script>
{% endblock %}

myrsrcmngr/website/templates/website/search.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Search results</h1>
    <ol class="breadcrumb mb-4">
        {% if searched %}
        <li class="breadcrumb-item active">You searched for: {{searched}}</li>
    </ol>
    <div class="row">
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    Groups
                </div>
                <div class="card-body">
                    <div class="card-body">
                        {% if foundresourcegroups %}
                        <ul class="list-group list-group-flush">
                            {% for group in foundresourcegroups %}
                            <li class="list-group-item list-group-item-action">
                              <a href="{% url 'website:groups-detail' group.id %}">{{group.name}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <p>No groups found </p>
                        {% endif %} 
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    Hosts
                </div>
                <div class="card-body">
                    {% if foundhosts %}
                        <ul class="list-group list-group-flush">
                            {% for host in foundhosts %}
                            <li class="list-group-item list-group-item-action">
                              <a href="{% url 'website:hosts-detail' host.id %}">{{host.main_address}}</a>
                            </li>
                            {% endfor %}
                    </ul>
                    {% else %}
                    <p>No hosts found </p>
                    {% endif %} 
                </div>
            </div>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Scans
        </div>
        <div class="card-body">
        {% if foundscans %}
            <table id="datatablesSimple" class="table">
                <thead>
                    <tr>
                        <th>Last execution at</th>
                        <th>Next execution at</th>
                        <th>Name</th>
                        <th>Current status</th>
                        <th>Active</th>
                        <th>Group</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Last execution at</th>
                        <th>Next execution at</th>
                        <th>Name</th>
                        <th>Current status</th>
                        <th>Active</th>
                        <th>Group</th>
                    </tr>
                </tfoot>
                <tbody>
                {% for scan in foundscans %}
                    <tr>
                        <td>{{ scan.last_executed }}</td>
                        <td>{{ scan.next_execution_at }}</td>
                        <td><a href="{% url 'website:scan-detail' scan.pk %}"> {{ scan.scanName }}</a></td>
                        {% if scan.status == 0 %}
                        <td class="table-success">DONE</td>
                        {% elif scan.status == 1 %}
                        <td class="table-success">READY</td>
                        {% elif scan.status == 2 %}
                        <td class="table-success">RUNNING</td>
                        {% elif scan.status == 3 %}
                        <td class="table-warning">CANCELLED</td>
                        {% elif scan.status == 4 %}
                        <td class="table-danger">FAILED</td>                        
                        {% else %}
                        <td class="table-default">NOT SET</td>
                        {% endif %}
                        {% if scan.active %}
                        <td class="table-success">ON</td>
                        {% else %}
                        <td class="table-info">OFF</td>
                        {% endif %}
                        <td><a href="{% url 'website:groups-detail' scan.resourcegroup.id %}"> {{ scan.resourcegroup }}</a></td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        {% else %}
            <p>No scans found</p>
        {% endif %}
        </div>
    </div>
    {% else %}
            <li class="breadcrumb-item active">No search term entered</li>
    </ol>
    {% endif %}
</div>
{% endblock %}