myrsrcmngr/myrsrcmngr/urls.py
from django.contrib import admin
from django.urls import path, include
from myrsrcmngr import views
from users.views import register, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resources/', views.Resource_list),
    path('', include('website.urls')),
    path('register/', register.as_view(), name='register'),
    #path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout-view'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('users.urls')),
]

myrsrcmngr/users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path('<int:pk>/', views.ProfileDetailView.as_view(), name = 'profile-home'),
    path('<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('<int:pk>/delete', views.ProfileDeleteView.as_view(), name='profile-delete'),
]

myrsrcmngr/website/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'website'
urlpatterns = [
    #Dashboard
    path('', views.dashboard, name='index'),
    
    #Dashboard API for AJAX calls
    path('dashboard/api/dismissed/', views.dashboard_dismiss, name='dashboard-dismiss'),
    path('dashboard/api/changes/', views.dashboard_changes, name='dashboard-changes'),
    path('changes/', views.dashboard_changes_table, name='changes-only'),
    path('dashboard/api/scans/', views.dashboard_scans, name='dashboard-scans'),
    
    #Scans CRUD
    path('scans/', views.ScansListView.as_view(), name='scans-list'),
    path('scans/create', views.ScanCreateView.as_view(), name='new-scan'),
    path('scans/<int:pk>', views.ScanDetailView.as_view(), name='scan-detail'),
    path('scans/<int:pk>/edit', views.ScanUpdateView.as_view(), name='edit-scan'),
    path('scans/<int:pk>/delete', views.ScanDeleteView.as_view(success_url=reverse_lazy('website:scans-list')), name='delete-scan'),
    
    #Scans API for AJAX calls
    path('scans/api/<int:pk>/', views.ScanProgressView.as_view(), name='scan-progress'),
    path('scans/api/toggle/<int:pk>/', views.scan_toggle, name='scan-toggle'),
    path('scans/api/refresh/scans/<int:pk>/', views.scan_refresh, name='reports-refresh'),
    path('scans/api/refresh/scans/', views.scanlist_refresh, name='scans-refresh'),
    path('scans/api/refresh/totals/', views.scanlist_totals_refresh, name='scans-totals'),

    #Resource groups CRUD
    path('groups/', views.ResourcegroupsListView.as_view(), name='groups-list'),
    path('groups/create', views.ResourcegroupCreateView.as_view(), name='new-group'),
    path('groups/<int:pk>/', views.ResourcegroupDetailView.as_view(), name='groups-detail'),
    path('groups/<int:pk>/edit', views.ResourcegroupUpdateView.as_view(), name='edit-group'),
    path('groups/<int:pk>/delete', views.ResourcegroupDeleteView.as_view(success_url=reverse_lazy('website:groups-list')), name='delete-group'),
    
    #Resource groups API for AJAX calls
    path('groups/api/refresh/groups/', views.grouplist_refresh, name='groups-refresh'),
    path('groups/api/refresh/scans/<int:pk>/', views.scans_group_refresh, name='scans-group-refresh'),
    path('groups/api/refresh/totals/', views.grouplist_totals_refresh, name='groups-totals'),
    path('groups/api/refresh/changes/<int:pk>/', views.group_changes_refresh, name='groups-changes'),
    path('groups/api/refresh/hosts/<int:pk>/', views.hostsgroup_refresh, name='hosts-refresh'),

    #Hosts CRUD
    path('hosts/', views.HostsListView.as_view(), name='hosts-list'),
    path('hosts/<int:pk>/', views.HostDetailView.as_view(), name='hosts-detail'),
    path('hosts/<int:pk>/edit', views.HostUpdateView.as_view(), name='edit-host'),
    
    #Hosts API for AJAX calls
    path('hosts/api/refresh/totals/', views.hosts_totals_refresh, name='hosts-totals'),
    path('hosts/api/refresh/hosts/', views.hosts_refresh, name='hosts-all-refresh'),
    path('hosts/api/refresh/changes/<int:pk>/', views.host_changes_refresh, name='host-changes'),
    path('hosts/api/refresh/services/<int:pk>/', views.host_services_refresh, name='host-services'),
    
    #Reports CRUD
    path('reports/', views.ReportsListView.as_view(), name='reports-list'),
    path('reports/<int:pk>', views.ReportDetailView.as_view(), name='report-detail'),
    path('reports/<int:pk>/download/', views.download_report, name='download_report'),
    
    #Reports API for AJAX calls 
    path('reports/api/toggle/<int:pk>/', views.set_standard_report, name='set-standard-report'),
    path('reports/api/refresh/totals/', views.reports_totals_refresh, name='reports-totals'),
    path('reports/api/refresh/reports/', views.reports_refresh, name='reports-all-refresh'),
    
    #Services CRUD
    path('services/<int:pk>', views.ServiceDetailView.as_view(), name='service-detail'),
    
    #Services API for AJAX calls
    
    
    #Search
    path('search/', views.GlobalSearch, name='search'),
    
    #Scans list JSON response
    path('scans/json/', views.scans_list),
    
    #Chart refresh API
    path('groups/api/chart/', views.groups_piechart, name='groups-chart'),
    path('scans/api/chart/', views.scans_chart, name='scans-chart'),
    path('hosts/api/chart/', views.hosts_chart, name='hosts-chart'),
    path('reports/api/chart/', views.reports_chart, name='reports-chart'),
    path('dashboard/api/chart/', views.dashboard_chart, name='dashboard-chart'),
]

myrsrcmngr/website/views.py
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import JsonResponse
from django.contrib.humanize.templatetags.humanize import naturaltime
from .serializers import ScansSerializer, ReportsSerializer, ResourcegroupsSerializer, HostsSerializer, ServicesSerializer
from rest_framework.decorators import api_view
from .owner import OwnerCreateView, OwnerUpdateView, OwnerDeleteView, GroupOwnerCreateView, GroupOwnerUpdateView, GroupOwnerDeleteView, HostOwnerUpdateView
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseNotAllowed
import os
import random
from django.db.models import Q
from django.utils import timezone
import logging
from django.db.models import Count



# Create your views here.
from .models import scans, hosts, reports, resourcegroups, services, changes
logger = logging.getLogger(__name__)

def index(request):
    con = {}
    rreport = None
    for rgroup in resourcegroups.objects.all().order_by('-updated_at')[:5]:
        
        try:
            rreport = rgroup.reports_set.latest('id')
            groupname = rgroup.name
            con[groupname] = rreport
        except:
            rreport = None
    context = {
        'con': con
    }
    return render(request, 'index.html', context)

def dashboard_changes_table(request):
    if request.method == 'GET':
        eachchanges = {}
        allchanges = []
        mainchanges = {'total': 0,
                        'changes': [{
                                    'main_address':'',
                                    'group_name':'',
                                    'group_id':0,
                                    'host_id':0,
                                    'report_date':'',
                                    'report_id':0,
                                    'attribute': '',
                                    'new_value': '',
                                    },
                                ]
                    }        
        #In order to relieve some data amount concerns, select just the last 100 successful reports
        reports_list = reports.objects.all().filter(parse_success=True).order_by('-id')[:100]

        #for each report, find the notable changes (status, state, os_fingerprint) that have not been dismissed, and are not the elapsed time
        #Further filter down for those changes that have host indicated
        filteredChanges = changes.objects.filter(cur_report__in=reports_list)
        filteredChanges = filteredChanges.exclude(dismissed=True).exclude(attribute='elapsed').exclude(host=None)
        filteredChanges = filteredChanges.filter(Q(attribute='status') | Q(attribute='state') | Q(attribute='os_fingerprint'))
        for change in filteredChanges:
            host = change.host
            group = host.resourcegroup
            eachchanges['main_address'] = host.main_address
            eachchanges['group_name'] = group.name
            eachchanges['group_id'] = group.id
            eachchanges['host_id'] = host.id
            eachchanges['report_date'] = change.cur_report.f_endtime_str()
            eachchanges['report_id'] = change.cur_report.id
            eachchanges['attribute'] = change.attribute
            if change.attribute == 'state' and change.cur_val == 'open':
                eachchanges['new_value'] = change.service.name_conc
            elif change.attribute == 'state':
                eachchanges = {}
                continue
            else:
                eachchanges['new_value'] = change.cur_val
            allchanges.append(eachchanges)
            eachchanges = {}
        mainchanges['total'] = len(allchanges)
        mainchanges['changes'] = allchanges
        return render(request, 'selected_changes.html', {'changes':mainchanges})

@api_view(['POST'])
def dashboard_dismiss(request):
    if request.method == 'POST':
        # get the last 100 reports
        last_100_reports = reports.objects.all().order_by('-id')[:100]
        # get all changes that relate to the last 100 reports
        filteredchanges = changes.objects.filter(cur_report__in=last_100_reports)
        # set the 'dismissed' attribute to True for all changes
        filteredchanges.update(dismissed=True)
        # return a JSON response indicating that the changes have been dismissed
        return JsonResponse({'dismissed': True})

@api_view(['GET'])
def dashboard_changes(request):
    if request.method == 'GET':
        eachchanges = {}
        allchanges = []
        mainchanges = {'total': 0,
                        'changes': [{
                                    'main_address':'',
                                    'group_name':'',
                                    'group_id':0,
                                    'host_id':0,
                                    'report_date':'',
                                    'report_id':0,
                                    'attribute': '',
                                    'new_value': '',
                                    },
                                ]
                    }        
        #In order to relieve some data amount concerns, select just the last 100 successful reports
        reports_list = reports.objects.all().filter(parse_success=True).order_by('-id')[:100]

        #for each report, find the notable changes (status, state, os_fingerprint) that have not been dismissed, and are not the elapsed time
        #Further filter down for those changes that have host indicated
        filteredChanges = changes.objects.filter(cur_report__in=reports_list)
        filteredChanges = filteredChanges.exclude(dismissed=True).exclude(attribute='elapsed').exclude(host=None)
        filteredChanges = filteredChanges.filter(Q(attribute='status') | Q(attribute='state') | Q(attribute='os_fingerprint'))
        for change in filteredChanges:
            host = change.host
            group = host.resourcegroup
            eachchanges['main_address'] = host.main_address
            eachchanges['group_name'] = group.name
            eachchanges['group_id'] = group.id
            eachchanges['host_id'] = host.id
            eachchanges['report_date'] = change.cur_report.f_endtime_str()
            eachchanges['report_id'] = change.cur_report.id
            eachchanges['attribute'] = change.attribute
            if change.attribute == 'state' and change.cur_val == 'open':
                eachchanges['new_value'] = change.service.name_conc
            elif change.attribute == 'state':
                eachchanges = {}
                continue
            else:
                eachchanges['new_value'] = change.cur_val
            allchanges.append(eachchanges)
            eachchanges = {}
        mainchanges['total'] = len(allchanges)
        mainchanges['changes'] = allchanges
        return JsonResponse({"data":mainchanges})


def dashboard(request):
    con = {}
    rreport = None
    report_changes = {}
    for rgroup in resourcegroups.objects.all().order_by('-updated_at'):
        
        try:
            rreport = rgroup.reports_set.latest('id')
            groupname = rgroup.name
            rchanges = rreport.changes_set.all().exclude(attribute='elapsed')
            changes_count = rchanges.count()
            if rchanges:
                report_changes['hosts_changed'] = 0
                report_changes['hosts_added'] = 0
                report_changes['hosts_removed'] = 0
                report_changes['services_changed'] = 0
                report_changes['services_added'] = 0
                report_changes['services_removed'] = 0
                report_changes['hosts_up'] = None
                report_changes['hosts_down'] = None
                report_changes['hosts_total'] = None
                counter = 0
                for change in rchanges:
                    counter = counter + 1
                    if change.attribute == 'hosts_up':
                        if change.prev_val is None:
                            change.prev_val = 0
                        report_changes['hosts_up'] = int(change.cur_val) - int(change.prev_val)
                    elif change.attribute == 'hosts_down':
                        if change.prev_val is None:
                            change.prev_val = 0
                        report_changes['hosts_down'] = int(change.cur_val) - int(change.prev_val)
                    elif change.attribute == 'hosts_total':
                        if change.prev_val is None:
                            change.prev_val = 0
                        report_changes['hosts_total'] = int(change.cur_val) - int(change.prev_val)
                    elif change.status == 'CHANGED' and change.host is not None and change.service is None:
                        report_changes['hosts_changed'] = report_changes['hosts_changed'] + 1
                    elif change.status == 'ADDED' and change.host is not None and change.service is not None:
                        report_changes['services_added'] = report_changes['services_added'] + 1
                    elif change.status == 'CHANGED' and change.host is not None and change.service is not None:
                        report_changes['services_changed'] = report_changes['services_changed'] + 1
                    elif change.status == 'REMOVED' and change.host is not None and change.service is not None:
                        report_changes['services_removed'] = report_changes['services_removed'] + 1
                    elif change.status == 'REMOVED' and change.host is not None and change.service is None:
                        report_changes['hosts_removed'] = report_changes['hosts_removed'] + 1
                    elif change.status == 'ADDED' and change.host is not None and change.service is None:
                        report_changes['hosts_added'] = report_changes['hosts_added'] + 1

myrsrcmngr/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Webapp to manage and schedule NMAP scans on your network" />
        <meta name="author" content="ad09009" />
        <title>My Resource Manager</title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'website/assets/img/favicon.png' %}">
        <link href="{% static 'website/css/styles.css' %}" type="text/css" rel="stylesheet" />
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->
        <link rel="stylesheet" type="text/css" href="{% static 'website/DataTables/datatables.css' %}">
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'website:index' %}">My Resource Manager</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" method="POST" action="{% url 'website:search' %}">
                {% csrf_token %}
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" name="searched"/>
                    <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'users:profile-home' user.profile.id %}">Profile</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'logout-view' %}">Logout</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Status</div>
                            <a class="nav-link" href="{% url 'website:index' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Overview</div>
                            <a class="nav-link collapsed" href="#" id="One" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Network
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="One" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'website:scans-list' %}">Scans</a>
                                    <a class="nav-link" href="{% url 'website:groups-list' %}">Groups</a>
                                    <a class="nav-link" href="{% url 'website:hosts-list' %}">Hosts</a>
                                    <a class="nav-link" href="{% url 'website:reports-list' %}">Reports</a>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        {% if user.is_authenticated %}
                        <div class="small">Logged in as:</div>
                        <a href="{% url 'users:profile-home' user.profile.id  %}">{{ user.username }}</a>
                        {% else %}
                        <div class="small">Not logged in</div>
                        {% endif %}
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    {% block content %}
                    {% endblock %}
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">&copy; MyRSRCMNGR 2022</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <script src="{% static 'website/jquery-3.6.1.min.js' %}"></script>
        <script src="{% static 'website/js/scripts.js' %}"></script>
        <script src="{% static 'website/DataTables/datatables.js' %}"></script>
        <script src="{% static 'js/Chart.min.js' %}"></script>
        <script src="{% static 'website/js/datatables-simple-demo.js' %}"></script>
        {% block js %}
        {% endblock %}
    </body>
</html>

myrsrcmngr/website/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container-fluid px-4">
        <h1 class="mt-4">Dashboard</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">An overview of notable changes</li>
        </ol>
        <div class="row">
            <div class="col-xl-4 col-md-4 d-flex">
                <div class="card mb-4 flex-fill">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Active Scans
                    </div>
                    <div class="card-body" id="dashInfo">
                        {% if activescans %}
                        <table id="datatablesSimpleDashScans" class="table" report-url="{% url 'website:dashboard-scans' %}">
                            <thead>
                                <tr>
                                    <th>Scan</th>
                                    <th>Group</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for scan in activescans %}
                                <tr>
                                    <td><a class="small" href="{% url 'website:scan-detail' scan.id %}">{{ scan.scanName }}</a></td>
                                    <td><a class="small" href="{% url 'website:groups-detail' scan.resourcegroup.id %}">{{ scan.resourcegroup }}</a></td>
                                    <td><h6 class="small">{{ scan.formatted_status }}</h6></td>
                                </tr>
                            {% endfor %}
            
                                </tbody>
                            </table>
                        {% else %}
                        <div class="row mx-auto text-center">
                            <div class="col-12 ">No Active Scans</div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small" href="{% url 'website:scans-list' %}">View Scans</a>
                        <div class="small"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-4">
                <div class="card bg-warning text-white mb-4">
                    <div class="card-body" id="dashboardChanges" data-ajax-target="{% url 'website:dashboard-changes' %}">
                        <div id="change-carousel" class="carousel slide">
                            <div class="carousel-inner" id="innerC">
                               
                                <div class="carousel-item active">
                                  <!-- Change details here -->
                                  
                                  <div class="card-body mx-auto text-center">
                                    <h5 class="card-title text-center">No New Changes</h5>
                                    <div class="row">
                                        <div class="col-6">Host: </div>
                                        <div class="col-6 text-right">-</div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-6">Group: </div>
                                        <div class="col-6 text-right">-</div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-6">Change: </div>
                                        <div class="col-6 text-right">-</div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-6">Report: </div>
                                        <div class="col-6 text-right">-</div>
                                    </div> 
                                    </div>
                                </div>
                               
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#change-carousel" data-bs-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#change-carousel" data-bs-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Next</span>
                            </button>
                          </div>                        
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <button id="dashboardDismiss" scan-ajax-target="{% url 'website:dashboard-dismiss' %}" value="0" class="btn btn-danger d-inline-block my-auto" disabled>Dismiss All</button>
                        <input type="hidden" id="active" value="{% if changes %}0{% else %}1{% endif %}">
                        <a id="allChanges" href="{% url 'website:changes-only' %}" class="btn btn-primary d-inline-block my-auto" disabled>View All {{changes.totals}} Changes</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-4 d-flex">
                <div class="card mb-4 flex-fill">
                    <div class="card-header">
                        <i class="fas fa-chart-bar me-1"></i>
                        Hosts UP per Group
                    </div>
                    <div class="card-body" id="dashchartWrapper" ajax-target="{% url 'website:dashboard-chart' %}">
                        <canvas id="dashboardChart" width="100%" height="40"></canvas></div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small" href="{% url 'website:hosts-list' %}">View Hosts</a>
                        <div class="small"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Recent Changes
            </div>
            <div class="card-body">
            {% if con %}
                <table id="datatablesSimple" class="table">
                    <thead>
                        <tr>
                            <th>Observed at</th>
                            <th>Parameters</th>
                            <th>Hosts Up</th>
                            <th>Hosts Down</th>
                            <th>Host Changes</th>
                            <th>Service Changes</th>
                            <th>Total Changes</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for key, value in con.items %}
                        <tr>
                            <td>{{ value.report.f_endtime_str }}</td>
                            <td><a href="{% url 'website:scan-detail' value.report.scan.id %}">{{ value.report.full_cmndline }}</a></td>
                            {% if value.changes and value.report_changes %}
                                {% if value.report_changes.hosts_up %}
                                <td>{{ value.report.hosts_up }} ({{value.report_changes.hosts_up}})</td>
                                {% else %}
                                <td>{{ value.report.hosts_up }}</td>
                                {% endif %}
                                {% if value.report_changes.hosts_down %}
                                <td>{{ value.report.hosts_down }} ({{value.report_changes.hosts_down}})</td>
                                {% else %}
                                <td>{{ value.report.hosts_down }}</td>
                                {% endif %}
                            {% else %}
                            <td>{{ value.report.hosts_up }}</td>
                            <td>{{ value.report.hosts_down }}</td>
                            {% endif %}
                            <td>{{ value.report_changes.hosts_changed }}</td>
                            <td>{{ value.report_changes.services_changed }}</td>
                            <td>{{ value.changes_count }}</td>
                        </tr>
                    {% endfor %}
    
                    </tbody>
                </table>
            {% else %}
                <p>There are no recent changes in any reports created by any scans in the database.</p>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
<script src="{% static 'website/js/dashboardupdate.js' %}"></script>
{% endblock js %}